stages:
  make_manifest:
    foreach: ${langs}  
    do:
      cmd: pixi run python scripts/make_manifest.py
        --wav-dir data/raw/${item}/wav
        --transcripts data/raw/${item}/transcripts.tsv
        --lang ${item}
        --output data/manifests/${item}/clean.jsonl
      deps:
        - scripts/make_manifest.py
        - data/raw/${item}/wav
        - data/raw/${item}/transcripts.tsv
      params:
        - langs   
      outs:
        - data/manifests/${item}/clean.jsonl


  add_noise:
    matrix:
      lang: ${langs}
      snr: ${snr_levels}
    cmd: pixi run python scripts/add_noise.py
      --clean-manifest data/manifests/${item.lang}/clean.jsonl
      --lang ${item.lang}
      --snr-db ${item.snr}
      --output-dir data/noisy/${item.lang}/${item.snr}db
      --output-manifest data/manifests/${item.lang}/noisy_${item.snr}db.jsonl
    deps:
      - scripts/add_noise.py
      - data/manifests/${item.lang}/clean.jsonl
    params:
      - langs
      - snr_levels
    outs:
      - data/manifests/${item.lang}/noisy_${item.snr}db.jsonl
      - data/noisy/${item.lang}/${item.snr}db


  run_asr:
    matrix:
      lang: ${langs}
      snr: ${snr_levels}
    cmd: pixi run python scripts/run_asr.py
      --input-manifest data/manifests/${item.lang}/noisy_${item.snr}db.jsonl
      --output-manifest data/preds/${item.lang}/preds_${item.snr}db.jsonl
    deps:
      - scripts/run_asr.py
      - data/manifests/${item.lang}/noisy_${item.snr}db.jsonl
    params:
      - langs
      - snr_levels
    outs:
      - data/preds/${item.lang}/preds_${item.snr}db.jsonl

  evaluate:
    matrix:
      lang: ${langs}
      snr: ${snr_levels}
    cmd: pixi run python scripts/evaluate.py
      --pred-manifest data/preds/${item.lang}/preds_${item.snr}db.jsonl
      --output results/metrics/${item.lang}_${item.snr}db.json
      --lang ${item.lang}
      --snr-db ${item.snr}
    deps:
      - scripts/evaluate.py
      - data/preds/${item.lang}/preds_${item.snr}db.jsonl
    params:
      - langs
      - snr_levels
    outs:
      - results/metrics/${item.lang}_${item.snr}db.json